### ISSUE TITLE
No OTA on NodeMCU (ESP8266MOD) with HL2.0?

### ISSUE THREAD

**Issue by Vayain** [thehookup/Holiday_LEDs_2.0#11]
Holiday Lights 1.0 are running like a charm on three NodeMCUs, Update through OTA is working.
An initial Update of the HL2.0 sketch to my NodeMCUs (ESP8266MOD) via OTA is working. 

While trying to change the HL2.0 sketch and update it again via OTA , i receive the error message "No Answer to our Authentication".
Update without OTA-authentication results in "No answer".

After some digging it seems that the new sketch consumes more memory space as HL1.0 resulting in too little free memory for OTA to flash?

**Comment by thehookup** [comment]
Huh, mine is OTA updating without any issue.  What settings are you using on the nodeMCU for upload?  Did you make sure the main light switch in HA is off?  It only runs the ArduinoOTA.handle when the lights are off.

**Comment by Vayain** [comment]
Thanks for your response - and thanks for the hint with the main light switch. I had to reboot the NodeMCU several times, used exactly the same settings, somehow it's working now *scratching my head*
So thanks a lot!

These are my settings, hopefully they are fine?
Board: "NodeMCU 1.0 (ESP-12E Module)"
Flash Size: "4M (3M SPIFFS)"
Debug port: "Disabled"
Debug Level: "None"
IwIP Variant: "v2 Lower Memory"
VTables: "Flash"
CPU Frequency: "80 MHz"
Upload Speed: "115200"
Erase Flash: "All Flash Contents"
Port: "<My NodeMCU> at <My IP>"

**Comment by thehookup** [comment]
Those settings look good to me, closing this issue.
