### ISSUE TITLE
Spooky Eyes Going to Fast

### ISSUE THREAD

**Issue by jmoery** [thehookup/Holiday_LEDs_2.0#17]
Living this work from you.  The amount of customization through home assistant is great.  I'm trying to get the spooky eyes going correctly and have a test strip of 60 LEDs right now.  I was paying with the w setting but they seem to be going way too fast.  If I put the w at the highest, I get no eyes.  Even one stop lower I get a ton of eyes changing constantly and don't really look like eyes.

**Comment by thehookup** [comment]
Fixed, adjusted the lower bounds from 0 to 210 on the chance.
