### ISSUE TITLE
Not sure this is an issue but a question APA102 lights

### ISSUE THREAD

**Issue by paulfecht** [thehookup/Holiday_LEDs_2.0#18]
Hello,

I'm not sure where to post this but I'm prototyping the setup while I wait for my SK6812 lights 
to come in.  Can you give me an idea of what I would hook the clock pin up to? Labeled CI and CO.... which I assume are Clock In and Clock Out.

**Comment by thehookup** [comment]
clock in is all you'd need to hook up, but you'll need to change the definitions of the LEDS in the sketch to APA102.
