### ISSUE TITLE
Add Static IP for Wifi.

### ISSUE THREAD

**Issue by dpackham** [thehookup/Holiday_LEDs_2.0#5]
Adding the option of a static IP will allow the ESP to boot much quicker.

**Comment by dpackham** [comment]
In the "user config section" as well to keep it clean

**Comment by thehookup** [comment]
I don't see this getting implemented.  I'm betting someone who wants a static IP can handle editing the 4 lines of code required for changing to static IP.

**Comment by dpackham** [comment]
This makes my ESP connect is two dots and without it sometimes takes minutes.

// Static IP address for the nodeMCU
// uncomment the below WIFI_STATIC_IP for a static IP and faster reconnects
//#define WIFI_STATIC_IP
//IPAddress ip(10, 1, 1, 190);
//IPAddress gateway(10, 1, 1, 1);
//IPAddress subnet(255, 255, 255, 0);

and below add

  ifdef WIFI_STATIC_IP
    WiFi.config(ip, gateway, subnet);
  #endif

above

  WiFi.persistent(false);
  WiFi.hostname(USER_MQTT_CLIENT_NAME);
  WiFi.begin(ssid, password);
